In [40]:
##help from geeks for geeks and scipy.org
#import numpy library
import numpy as np
#import linalg function from SciPy [linalg=linear algebra]
from scipy import linalg
a = np.array([[1,3,5],[2,4,6],[2,3,1]])
print(linalg.det(a)) #Compute determinant of a matrix
a #print

6.000000000000002


array([[1, 3, 5],
       [2, 4, 6],
       [2, 3, 1]])

#Compute pivoted LU decomposition of a matrix
The decomposition is: 
A = P L U

where P is a permutation matrix, L lower triangular with unit diagonal elements, and U upper triangular.

In [46]:
p, l, u = linalg.lu(a)
print(p)
print(l)
print(u)
#print LU decomposition
np.dot(l,u)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [ 1.  -1.   1. ]]
[[ 2.  4.  6.]
 [ 0.  1.  2.]
 [ 0.  0. -3.]]


array([[2., 4., 6.],
       [1., 3., 5.],
       [2., 3., 1.]])

In [51]:
#Eigen values and eigen vectors of this matrix
eigen_values, eigen_vectors = linalg.eig(a)
print(eigen_values)
print(eigen_vectors)

[ 8.88855039+0.j -0.25645992+0.j -2.63209047+0.j]
[[-0.54126953 -0.79014274 -0.57461754]
 [-0.7311422   0.5924905  -0.44696568]
 [-0.41528107 -0.15693776  0.68559198]]


In [53]:
#sloving system of linear equations 
v = np.array([[2],[3],[5]])
print(v)
s = linalg.solve(a,v)
print(s)

[[2]
 [3]
 [5]]
[[-0.33333333]
 [ 2.16666667]
 [-0.83333333]]


In [59]:
#how to construct a large sparse matrix
from scipy import sparse
# Row-based linked list sparse matrix
a = sparse.lil_matrix((1000,1000))
print(a)
# output: <1000x1000 sparse matrix of type ''
#     with 0 stored elements in LInked List format>


a[0, :100] = np.random.rand(100)
a[1,100:200] = a[0, :100]
a.setdiag(np.random.rand(1000))
print(a)
#output: <1000x1000 sparse matrix of type ''
 #   with 1199 stored elements in LInked List format>


  (0, 0)	0.5818458415902479
  (0, 1)	0.8431965021742371
  (0, 2)	0.7089068196209397
  (0, 3)	0.165127098564108
  (0, 4)	0.011901490796016434
  (0, 5)	0.02529859466660611
  (0, 6)	0.7603818975344588
  (0, 7)	0.8729275584959938
  (0, 8)	0.37472502620871273
  (0, 9)	0.7918959366201377
  (0, 10)	0.22034920153356574
  (0, 11)	0.542083326892601
  (0, 12)	0.03937019780011819
  (0, 13)	0.6903393878793442
  (0, 14)	0.30092707027203447
  (0, 15)	0.3161332776029393
  (0, 16)	0.9407811436209277
  (0, 17)	0.6621486464350755
  (0, 18)	0.3794291663952889
  (0, 19)	0.9552295752676944
  (0, 20)	0.783140274033187
  (0, 21)	0.04173840736829393
  (0, 22)	0.18324276924134275
  (0, 23)	0.23378129766152544
  (0, 24)	0.9621216952596611
  (0, 25)	0.08285477357174176
  (0, 26)	0.7318581359328852
  (0, 27)	0.3965461232372338
  (0, 28)	0.9793986543803422
  (0, 29)	0.7185908008462614
  (0, 30)	0.11534852312037447
  (0, 31)	0.39456676643341393
  (0, 32)	0.7940360988029674
  (0, 33)	0.12328935450833378
  (0, 34)	0.

In [61]:
#linear algebra for Sparse Matrices
from scipy.sparse import  linalg
# Convert this matrix to Compressed Sparse Row format.
a = a.tocsr()
b = np.random.rand(1000)
ans = linalg.spsolve(a,b)
print(ans) #array of 1000 size

[-2.44748804e+03 -6.55621962e+02  4.68018978e-01  8.47724582e-01
  9.51462560e-01  4.50314035e+00  2.23663848e-01  5.89078464e+00
  8.63326599e-01  1.08656708e+00  8.43415221e-01  1.13479215e+00
  3.25855167e+00  2.92331560e-01  1.87281353e+00  3.20366281e-01
  1.38646831e-01  2.79732128e+00  1.00431782e+00  7.75546355e-01
  6.23320794e+00  1.88108970e+00  4.58890634e+00  6.60394443e-03
  7.78771686e-01  2.43887619e+00  3.35423089e+01  1.04861551e+00
  4.85422714e+00  7.64300440e-01  1.24675218e-01  3.12043706e-01
  1.22208854e+00  2.98022342e+00  5.79592024e-01  2.60140722e+01
  2.04896518e-01  1.33184580e+00  1.77760145e+00  1.27270425e+00
  5.45994792e+00  6.47789328e+00  1.00393357e+02  5.04132846e-01
  6.21985532e-01  4.89027865e-01  1.02698858e+00  4.29727357e+00
  6.02914455e-01  3.37906475e+00  2.22819321e+00  2.21660741e+03
  5.16416942e-01  1.61037386e-01  2.44703523e-01  3.32266025e-01
  1.10328161e-01  3.55432599e-01  1.12985377e+00  4.99777849e-01
  8.06691470e-01  2.75201

Integration: SciPy has integration methods in scipy.integrate module.
 
integrating e^{-x^2} over the range of 0 and 1 with respect to dx.
We will first define the function f(x)=e^(-x^2) , this is done using a lambda expression and then use quad routine.

In [63]:
import scipy.integrate
f = lambda x:np.exp(-x**2)
i = scipy.integrate.quad(f, 0, 1)
print(i) #first number value of integral and second means value of probable error

(0.7468241328124271, 8.291413475940725e-15)


Double Integrals: function is scipy.integrate.dblquad(f,a,b,g,h)
Where, f is funtction of integrated, a and b are the lower and upper limits of the x variable.Also, g and h are the lower and upper ranges of the y variable.

As an example, let us perform the double integral of x*y^2 over x range from 0 to 2 and y ranges from 0 to 1.

In [64]:
from scipy import integrate
f = lambda y, x: x*y**2
i = integrate.dblquad(f, 0, 2, lambda x: 0, lambda x: 1)
print(i)

(0.6666666666666667, 7.401486830834377e-15)
